connector.name=mysql
connection-url=jdbc:mysql://mysql:3306
connection-user=root
connection-password=root
case-insensitive-name-matching=true
unsupported-type-handling=CONVERT_TO_VARCHAR
decimal-mapping=allow_overflow
